### ISSUE TITLE
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

### ISSUE THREAD

**Issue by kevinlemon** [tobiascz/VideoPose3D#19]
Hello. When I try to implement your code "run_wild.py". I meet the following problem:
"
Traceback (most recent call last):
  File "run_wild.py", line 310, in <module>
    input_video_skip=args.viz_skip)
  File "/media/blaire/Data/MyCode/VideoPose3D-another/common/visualization.py", line 84, in render_animation
    ax.set_aspect('equal')
  File "/home/blaire/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1281, in set_aspect
    'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes
"
Could you give me some advice? Thank you so much!

**Comment by acfhs** [comment]
matplotlib==3.0.3
